name: Cloudflare Worker Examples CI

on: [pull_request]

jobs:
  ingest-only-example:
    runs-on: ubuntu-latest
    name: 'Ingest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install
        run: npm install
        working-directory: ./examples/IngestOnly
      - name: Build
        run: npm run build
        working-directory: ./examples/IngestOnly
      # - name: Test
      #   run: npm run test
      #   working-directory: ./examples/IngestOnly
  mitigate-and-ingest-example:
    runs-on: ubuntu-latest
    name: 'Mitigation & Ingest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install
        run: npm install
        working-directory: ./examples/MitigationAndIngest
      - name: Build
        run: npm run build
        working-directory: ./examples/MitigationAndIngest
      - name: Test
        run: npm run test
        working-directory: ./examples/MitigationAndIngest
        