name: Cloudflare Worker Examples CI

on: [pull_request]

jobs:
  ingest-only-example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Ingest'
        with:
          node-version: '12.x'
      - run: cd ./exmples/IngestOnly
      - run: npm i
      - run: npm run build
      - run: npm run test
  mitigate-andingest-example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Mitigation & Ingest'
        with:
          node-version: '12.x'
      - run: cd ./exmples/MitigationAndIngest
      - run: npm i
      - run: npm run test
      - run: npm run build