name: Cloudflare Worker Examples CI

on: [pull_request]

jobs:
  mitigate-and-ingest-example:
    runs-on: ubuntu-latest
    name: 'Mitigation & Ingest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install
        run: npm install
        working-directory: ./examples/MitigationAndIngest
      - name: Build
        run: npm run build
        working-directory: ./examples/MitigationAndIngest
      # - name: Test
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'
      # - run: |
      #   cd ./examples/MitigationAndIngest
      #   npm install
      #   npm run test


    # steps:
    #   - name: 'Test'
    #     with:
    #       node-version: '12.x'
    #     run: |
    #       cd ./exmples/MitigationAndIngest
    #       npm i
    #       npm run test
