name: Cloudflare Worker Examples CI

on: [pull_request]

jobs:
  mitigate-and-ingest-example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build Mitigation & Ingest'
        with:
          node-version: '12.x'
        run: |
          cd ./exmples/MitigationAndIngest
          npm i
          npm run build
    steps:
      - name: 'Test Mitigation & Ingest'
        with:
          node-version: '12.x'
        run: |
          cd ./exmples/MitigationAndIngest
          npm run test
